### ISSUE TITLE
TypeError: write() argument must be str, not bytes

### ISSUE THREAD

**Issue by pecheny** [sv99/lsdreader#12]
Following lines at lsdreader.py :
```
if sys.platform.startswith("win"):
    sys.stdout = codecs.getwriter('utf-8')(sys.stdout)
```
cause given error for me. Python 3.7.2 / Win10 x64
Wiping those lines out fixes the issue.

**Comment by Andrew-Archer** [comment]
Same behavior on Win 11 Python 3.11.0. Suggested fix works perfect. Thank you, @pecheny !
