### ISSUE TITLE
Problems with converting

### ISSUE THREAD

**Issue by mcalexdee** [sv99/lsdreader#8]
Hi,
I've tried to convert several times lsd to dsl but couldn't do it. Could you help me please and convert 3 files from a link below? 
https://drive.google.com/open?id=0ByNpWAXFWnF_X0hKYmN4T0s4dzg

**Comment by sv99** [comment]
https://drive.google.com/open?id=0B6bJQUIZURGpQWF2S3hHT0ppYVE

**Comment by mcalexdee** [comment]
Thanks
